### ISSUE TITLE
Image upload 

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW3#25]
I have made some picture in power point with the help of snipping tool cut and copied that picture. But i am unable to post in my documentation. Can anyone help?

**Comment by avgagliardo** [comment]
you mean in your markdown file?

**Comment by avgagliardo** [comment]
> I have made some picture in power point with the help of snipping tool cut and copied that picture. But i am unable to post in my documentation. Can anyone help?

Here are [the docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images) for inserting images into markdown

So for example if you have a screenshot, instead of uploading the file directly to github or using it in the document you would upload to a host, acquire that media link and then use markdown to associate the image.

So the block:
```
![octofriend](https://cameronmcefee.com/img/work/the-octocat/original.jpg "octofriend")
```
Will produce:

![octofriend](https://cameronmcefee.com/img/work/the-octocat/original.jpg "octofriend")

**Comment by Priyanka-43** [comment]
Yes, in my markdown file.

**Comment by avgagliardo** [comment]
Let me know if its still giving you trouble, maybe I can be more specific.

**Comment by Priyanka-43** [comment]
![Screenshot 2024-10-13 164423](https://github.com/user-attachments/assets/25840c22-e22b-402f-86fb-426b548127b3)
It's not working. This is the link of image.

**Comment by Priyanka-43** [comment]
Always it is working here only.

**Comment by avgagliardo** [comment]
Can you link me to the file where its not working?

**Comment by Priyanka-43** [comment]
Yeah sure. I am new to this Github. Can you please tell me how to do that?

**Comment by avgagliardo** [comment]
I think I might see the issue.

So first thing is that any files you can navigate to in your repositories (if they are public), you can just copy and paste the url directly from that page to link people to that file. But in this case, I think I found it already.

Is this [the file](https://github.com/Priyanka-43/CP1-24-HW3/blob/Documentation_MagneticFieldOfStraightLine/Magnetic%20Field%20of%20Straight%20wire%20wire%20line) that is giving you issues?

First thing I would do is remove the whitespaces from the filename (replace with underscores or camelcasing) to avoid filename issues. 

Also, make sure the filename ends with .md otherwise it will not be recognized as a markdown file and will be displayed as cleartext rather then rendered markdown.

If that doesn't help let me know!

**Comment by Priyanka-43** [comment]
Yes, this is the file. Sure i will make changes and let you know.

**Comment by avgagliardo** [comment]
> Always it is working here only.

Also it might be worth noting that github checks for properly formed markdown inside of these comments and automatically parses/renders it, so you don't need to worry about things like file extensions if you aren't placing it into a dedicated markdown file. That's probably why the link is working inside of issues conversations for you.

**Comment by Priyanka-43** [comment]
Hey, it worked. Thankyou so much for your help.

**Comment by avgagliardo** [comment]
Awesome, anytime!

**Comment by Priyanka-43** [comment]
I am closing this issue. Thankyou so much again.
