### ISSUE TITLE
A question about iterators.

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW3#50]
Is there a fundamental difference between iterators in Python and the concept of pointers in C/C++ ?

**Comment by avgagliardo** [comment]
With respect to datatypes, they are **very** different. C++ requires you to be very explicit with your data types while using iterators, in python they _just work_.

It takes a little bit of getting used to, because it seems like you are working with less information but the iterator objects are actually very "smart" and their uses generally conform to the same set of patterns.

Here are [some docs on python iterators](https://www.w3schools.com/python/python_iterators.asp).

**Comment by HeshamElsaman** [comment]
Thanks, a lot!
