### ISSUE TITLE
PR closing

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW3#51]
Why does PR need to be done before "class" if today's a holiday and a break away from school. If we have tomorrow and Wednesday which is a working class day to do the reviews then what's the point of having a deadline that not until midnight?

**Comment by avgagliardo** [comment]
> Why does PR need to be done before "class" if today's a holiday and a break away from school. If we have tomorrow and Wednesday which is a working class day to do the reviews then what's the point of having a deadline that not until midnight?

I think its because writing software this way (as a group using source control) is such a push/pull process that you need some time for both people on each end to do their parts. Writing code takes time, reviewing code takes time, making the necessary changes to that code.... takes time, etc. 

The sooner we all start the codedance the faster we can start rolling out useful systems.

**Comment by dnxjay** [comment]
That's understandable but we have kept it to the end of the day all semester so far seems kind of unfair to change that on a day we arent at school

**Comment by avgagliardo** [comment]
I cant speak to the policy itself, I just know what not having headroom to work does to a team (from learning it the hard way lol)

**Comment by kylemasc917** [comment]
Also changing deadlines is pretty commonplace in a number of environments so I wouldn't be surprised given the nature of previous assignments that isn't also one of the goals of that particular change.
